spring:
  application:
    name: skawallet

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/skawallet_db}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

    jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    show-sql: true

    server:
      port: ${PORT:8080}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liTlEqpEsFQSJNOa
            client-secret: b51b8b40c0270ebcf7e93c238c7d8eab07a79c06
            scope: read:user, user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

jwt:
  expiration: 3600000 # Expiração do JWT (1 hora)
  
paddle:
  api:
    base-url: https://vendors.paddle.com/api/2.0
    vendor-id: 210608
    api-key: c60a0a7f5ab2832a043a91244506815660b06e58809fbe389f
